#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file '../01_altera_ip/soc_system/soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'avalon_h2f', class 'altera_merlin_slave_translator'
 * The macros are prefixed with 'AVALON_H2F_'.
 * The prefix is the slave descriptor.
 */
#define AVALON_H2F_COMPONENT_TYPE altera_merlin_slave_translator
#define AVALON_H2F_COMPONENT_NAME avalon_h2f
#define AVALON_H2F_BASE 0x0
#define AVALON_H2F_SPAN 16777216
#define AVALON_H2F_END 0xffffff

/*
 * Macros for device 'avalon_h2f_lw', class 'altera_merlin_slave_translator'
 * The macros are prefixed with 'AVALON_H2F_LW_'.
 * The prefix is the slave descriptor.
 */
#define AVALON_H2F_LW_COMPONENT_TYPE altera_merlin_slave_translator
#define AVALON_H2F_LW_COMPONENT_NAME avalon_h2f_lw
#define AVALON_H2F_LW_BASE 0x0
#define AVALON_H2F_LW_SPAN 262144
#define AVALON_H2F_LW_END 0x3ffff

/*
 * Macros for device 'sysid_qsys_0', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_QSYS_0_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_QSYS_0_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_QSYS_0_COMPONENT_NAME sysid_qsys_0
#define SYSID_QSYS_0_BASE 0x40010
#define SYSID_QSYS_0_SPAN 8
#define SYSID_QSYS_0_END 0x40017
#define SYSID_QSYS_0_ID 305419896
#define SYSID_QSYS_0_TIMESTAMP 1524011446

/*
 * Macros for device 'led_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'LED_PIO_'.
 * The prefix is the slave descriptor.
 */
#define LED_PIO_COMPONENT_TYPE altera_avalon_pio
#define LED_PIO_COMPONENT_NAME led_pio
#define LED_PIO_BASE 0x40020
#define LED_PIO_SPAN 16
#define LED_PIO_END 0x4002f
#define LED_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define LED_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LED_PIO_CAPTURE 0
#define LED_PIO_DATA_WIDTH 8
#define LED_PIO_DO_TEST_BENCH_WIRING 0
#define LED_PIO_DRIVEN_SIM_VALUE 0
#define LED_PIO_EDGE_TYPE NONE
#define LED_PIO_FREQ 50000000
#define LED_PIO_HAS_IN 0
#define LED_PIO_HAS_OUT 1
#define LED_PIO_HAS_TRI 0
#define LED_PIO_IRQ_TYPE NONE
#define LED_PIO_RESET_VALUE 0

/*
 * Macros for device 'h2f_lw_ram', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'H2F_LW_RAM_'.
 * The prefix is the slave descriptor.
 */
#define H2F_LW_RAM_COMPONENT_TYPE altera_avalon_onchip_memory2
#define H2F_LW_RAM_COMPONENT_NAME h2f_lw_ram
#define H2F_LW_RAM_BASE 0x41000
#define H2F_LW_RAM_SPAN 16
#define H2F_LW_RAM_END 0x4100f
#define H2F_LW_RAM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 1
#define H2F_LW_RAM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define H2F_LW_RAM_CONTENTS_INFO ""
#define H2F_LW_RAM_DUAL_PORT 0
#define H2F_LW_RAM_GUI_RAM_BLOCK_TYPE AUTO
#define H2F_LW_RAM_INIT_CONTENTS_FILE soc_system_h2f_lw_ram
#define H2F_LW_RAM_INIT_MEM_CONTENT 1
#define H2F_LW_RAM_INSTANCE_ID lwrm
#define H2F_LW_RAM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define H2F_LW_RAM_RAM_BLOCK_TYPE AUTO
#define H2F_LW_RAM_READ_DURING_WRITE_MODE DONT_CARE
#define H2F_LW_RAM_SINGLE_CLOCK_OP 0
#define H2F_LW_RAM_SIZE_MULTIPLE 1
#define H2F_LW_RAM_SIZE_VALUE 16
#define H2F_LW_RAM_WRITABLE 1
#define H2F_LW_RAM_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define H2F_LW_RAM_MEMORY_INFO_GENERATE_DAT_SYM 1
#define H2F_LW_RAM_MEMORY_INFO_GENERATE_HEX 1
#define H2F_LW_RAM_MEMORY_INFO_HAS_BYTE_LANE 0
#define H2F_LW_RAM_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define H2F_LW_RAM_MEMORY_INFO_MEM_INIT_DATA_WIDTH 32
#define H2F_LW_RAM_MEMORY_INFO_MEM_INIT_FILENAME soc_system_h2f_lw_ram

/*
 * Macros for device 'cnn_inst_info', class 'altera_avalon_pio'
 * The macros are prefixed with 'CNN_INST_INFO_'.
 * The prefix is the slave descriptor.
 */
#define CNN_INST_INFO_COMPONENT_TYPE altera_avalon_pio
#define CNN_INST_INFO_COMPONENT_NAME cnn_inst_info
#define CNN_INST_INFO_BASE 0x42000
#define CNN_INST_INFO_SPAN 16
#define CNN_INST_INFO_END 0x4200f
#define CNN_INST_INFO_BIT_CLEARING_EDGE_REGISTER 0
#define CNN_INST_INFO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CNN_INST_INFO_CAPTURE 0
#define CNN_INST_INFO_DATA_WIDTH 32
#define CNN_INST_INFO_DO_TEST_BENCH_WIRING 0
#define CNN_INST_INFO_DRIVEN_SIM_VALUE 0
#define CNN_INST_INFO_EDGE_TYPE NONE
#define CNN_INST_INFO_FREQ 50000000
#define CNN_INST_INFO_HAS_IN 1
#define CNN_INST_INFO_HAS_OUT 0
#define CNN_INST_INFO_HAS_TRI 0
#define CNN_INST_INFO_IRQ_TYPE NONE
#define CNN_INST_INFO_RESET_VALUE 0

/*
 * Macros for device 'video_block_number', class 'altera_avalon_pio'
 * The macros are prefixed with 'VIDEO_BLOCK_NUMBER_'.
 * The prefix is the slave descriptor.
 */
#define VIDEO_BLOCK_NUMBER_COMPONENT_TYPE altera_avalon_pio
#define VIDEO_BLOCK_NUMBER_COMPONENT_NAME video_block_number
#define VIDEO_BLOCK_NUMBER_BASE 0x43000
#define VIDEO_BLOCK_NUMBER_SPAN 16
#define VIDEO_BLOCK_NUMBER_END 0x4300f
#define VIDEO_BLOCK_NUMBER_BIT_CLEARING_EDGE_REGISTER 0
#define VIDEO_BLOCK_NUMBER_BIT_MODIFYING_OUTPUT_REGISTER 0
#define VIDEO_BLOCK_NUMBER_CAPTURE 0
#define VIDEO_BLOCK_NUMBER_DATA_WIDTH 32
#define VIDEO_BLOCK_NUMBER_DO_TEST_BENCH_WIRING 0
#define VIDEO_BLOCK_NUMBER_DRIVEN_SIM_VALUE 0
#define VIDEO_BLOCK_NUMBER_EDGE_TYPE NONE
#define VIDEO_BLOCK_NUMBER_FREQ 50000000
#define VIDEO_BLOCK_NUMBER_HAS_IN 1
#define VIDEO_BLOCK_NUMBER_HAS_OUT 0
#define VIDEO_BLOCK_NUMBER_HAS_TRI 0
#define VIDEO_BLOCK_NUMBER_IRQ_TYPE NONE
#define VIDEO_BLOCK_NUMBER_RESET_VALUE 0

/*
 * Macros for device 'pd_bbox_frame', class 'altera_avalon_pio'
 * The macros are prefixed with 'PD_BBOX_FRAME_'.
 * The prefix is the slave descriptor.
 */
#define PD_BBOX_FRAME_COMPONENT_TYPE altera_avalon_pio
#define PD_BBOX_FRAME_COMPONENT_NAME pd_bbox_frame
#define PD_BBOX_FRAME_BASE 0x44000
#define PD_BBOX_FRAME_SPAN 16
#define PD_BBOX_FRAME_END 0x4400f
#define PD_BBOX_FRAME_BIT_CLEARING_EDGE_REGISTER 0
#define PD_BBOX_FRAME_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PD_BBOX_FRAME_CAPTURE 0
#define PD_BBOX_FRAME_DATA_WIDTH 8
#define PD_BBOX_FRAME_DO_TEST_BENCH_WIRING 0
#define PD_BBOX_FRAME_DRIVEN_SIM_VALUE 0
#define PD_BBOX_FRAME_EDGE_TYPE NONE
#define PD_BBOX_FRAME_FREQ 50000000
#define PD_BBOX_FRAME_HAS_IN 0
#define PD_BBOX_FRAME_HAS_OUT 1
#define PD_BBOX_FRAME_HAS_TRI 0
#define PD_BBOX_FRAME_IRQ_TYPE NONE
#define PD_BBOX_FRAME_RESET_VALUE 0

/*
 * Macros for device 'pd_bbox_h2f_lw', class 'altera_merlin_slave_translator'
 * The macros are prefixed with 'PD_BBOX_H2F_LW_'.
 * The prefix is the slave descriptor.
 */
#define PD_BBOX_H2F_LW_COMPONENT_TYPE altera_merlin_slave_translator
#define PD_BBOX_H2F_LW_COMPONENT_NAME pd_bbox_h2f_lw
#define PD_BBOX_H2F_LW_BASE 0x48000
#define PD_BBOX_H2F_LW_SPAN 16384
#define PD_BBOX_H2F_LW_END 0x4bfff

/*
 * Macros for device 'h2f_ram', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'H2F_RAM_'.
 * The prefix is the slave descriptor.
 */
#define H2F_RAM_COMPONENT_TYPE altera_avalon_onchip_memory2
#define H2F_RAM_COMPONENT_NAME h2f_ram
#define H2F_RAM_BASE 0x1000000
#define H2F_RAM_SPAN 256
#define H2F_RAM_END 0x10000ff
#define H2F_RAM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 1
#define H2F_RAM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define H2F_RAM_CONTENTS_INFO ""
#define H2F_RAM_DUAL_PORT 0
#define H2F_RAM_GUI_RAM_BLOCK_TYPE AUTO
#define H2F_RAM_INIT_CONTENTS_FILE soc_system_h2f_ram
#define H2F_RAM_INIT_MEM_CONTENT 1
#define H2F_RAM_INSTANCE_ID h2fr
#define H2F_RAM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define H2F_RAM_RAM_BLOCK_TYPE AUTO
#define H2F_RAM_READ_DURING_WRITE_MODE DONT_CARE
#define H2F_RAM_SINGLE_CLOCK_OP 0
#define H2F_RAM_SIZE_MULTIPLE 1
#define H2F_RAM_SIZE_VALUE 256
#define H2F_RAM_WRITABLE 1
#define H2F_RAM_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define H2F_RAM_MEMORY_INFO_GENERATE_DAT_SYM 1
#define H2F_RAM_MEMORY_INFO_GENERATE_HEX 1
#define H2F_RAM_MEMORY_INFO_HAS_BYTE_LANE 0
#define H2F_RAM_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define H2F_RAM_MEMORY_INFO_MEM_INIT_DATA_WIDTH 128
#define H2F_RAM_MEMORY_INFO_MEM_INIT_FILENAME soc_system_h2f_ram


#endif /* _ALTERA_HPS_0_H_ */
