`define		VGA_H_BIAS			32'D120	// 横向的像素点偏移
`define		VGA_V_BIAS			32'D110	// 纵向的像素点偏移
`define		VGA_H_WIDTH			32'D400	// 横向的像素点宽度
`define		VGA_V_WIDTH			32'D300	// 纵向的像素点宽度

`define		CAM_H_WIDTH			32'D800
`define		CAM_V_WIDTH			32'D600

/*
`define		MON_H_WIDTH			32'D800
`define		MON_V_WIDTH			32'D600
`define		MON_H_BIAS			32'D0
`define		MON_V_BIAS			32'D0
*/

`define		WORD_H_WIDTH		32'D199
`define		WORD_V_WIDTH		32'D50
`define		WORD_H_BIAS			32'D320
`define		WORD_V_BIAS			32'D300

`define		TITLE_H_WIDTH		32'D600
`define		TITLE_V_WIDTH		32'D35
`define		TITLE_H_BIAS		32'D20
`define		TITLE_V_BIAS		32'D10

/*
`define		ITU_H_WIDTH			32'D1728
`define		ITU_V_WIDTH			32'D625
*/

`define		RAM_READ_LATENCY	32'D3